app:
  env: "development"
  port: 8081
  context_path: "/classroom-gateway"
endpoint:
  classroom_listener:
    host: "http://localhost:8084"
    method: "GET"
    path:
      list: "/classroom-listener/api/v1/class-rooms"
      id: "/classroom-listener/api/v1/class-rooms/:id"
      slug: "/classroom-listener/api/v1/class-rooms/slug/:slug"
gin:
  mode: "debug"
  version: "v1"
  root_path: "api"
  configs:
    trusted_proxies: "127.0.0.1"
